{{--












































@endsection</div>    </div>        </form>            </div>                <a href="{{ route('register') }}" class="text-sm text-indigo-600 hover:text-indigo-900">Register</a>                </button>                    Login                <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">            <div class="flex items-center justify-between">            </div>                @enderror                    <p class="mt-1 text-sm text-red-600">{{ $message }}</p>                @error('password')                       class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">                <input id="password" type="password" name="password" required                <label for="password" class="block text-sm font-medium text-gray-700">Password</label>            <div class="mb-4">            </div>                @enderror                    <p class="mt-1 text-sm text-red-600">{{ $message }}</p>                @error('email')                       class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">                <input id="email" type="email" name="email" value="{{ old('email') }}" required autofocus                <label for="email" class="block text-sm font-medium text-gray-700">Email</label>            <div class="mb-4">            @csrf        <form method="POST" action="{{ route('login') }}">        <h2 class="text-2xl font-bold text-center mb-6">Login to Library System</h2>    <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg"><div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">@section('content')@section('title', 'Login')@extends('layouts.app')--}}Fitur: Input email/password, tombol login, link register, error display.Struktur: Extends layout app, section content dengan form login.Fungsi: Halaman login untuk autentikasi user.
