<?php












































}    }        ));            'popularBooks'            'borrowingsPerMonth',            'returnedBorrowings',            'totalCategories',            'activeBorrowings',            'totalMembers',            'totalBooks',        return view('dashboard', compact(            ->get();            ->take(5)            ->orderBy('borrowing_details_count', 'desc')        $popularBooks = Book::withCount('borrowingDetails')        // Buku terpopuler (berdasarkan jumlah peminjaman)            ->toArray();            ->pluck('count', 'month')            ->groupBy('month')            ->whereYear('borrow_date', date('Y'))        $borrowingsPerMonth = Borrowing::selectRaw('MONTH(borrow_date) as month, COUNT(*) as count')        // Data untuk chart (opsional, bisa pakai Chart.js nanti)        $returnedBorrowings = Borrowing::where('status', 'returned')->count();        $totalCategories = Category::count();        $activeBorrowings = Borrowing::where('status', 'borrowed')->count();        $totalMembers = Member::count();        $totalBooks = Book::sum('stock');        // Statistik dasar    {    public function index(){class DashboardController extends Controlleruse Illuminate\Http\Request;use App\Models\Category;use App\Models\Borrowing;use App\Models\Member;use App\Models\Book;namespace App\Http\Controllers;
